---
title: "snow_hare"
author: "Oswaldo Felix"
date: "2/1/2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

# Introduction

Snowshoe hares are an important prey species. This project uses weight recordings over a 

## Snowshoe Hare

Insert cute photographs and map of study area

### Citations

Data from: Kielland K., F. S. Chapin, R. W. Ruess. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14.  


```{r, include = FALSE}
# Load libraries and data

library(tidyverse)
library(here)
library(lubridate)
library(kableExtra)

hare_df <- read_csv(here::here("data", "showshoe_lter.csv"))

# Wrangle data

hare_select <- hare_df %>% 
  select(-time, -notes) %>% 
  mutate(date = mdy(date),
         year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date)
          ) %>% 
  mutate(age = case_when(age %in% c("J", "j", "J 3/4") ~ "Juvenile",
                         age %in% c("A", "a 1 yr.", "a 3/4 yr.", "a 1 yr", 
                                    "1 yr.", "2 yrs.", "a 2 yrs.", "2.25 yrs", 
                                    "3.5 yrs.", "1 yr", "2 yrs", "a", "1", "1.25", 
                                    "1.5", "A 3/4", "A 1/2", "3 yrs.", "2.5 yrs",
                                    "3.25 yrs.", "A 1.5") ~ "Adult",
                         age %in% c("NA", "u", "?", "U", "3/4/13", "1/4/13", "1/2/13") ~ "Mort")
  ) %>%
  mutate(season = case_when(month %in% c(4:9) ~ "Summer",
                            month %in% c(1:3, 10:12) ~ "Winter"
                            )
  )
```


```{r, fig.width = 10, fig.height = 5}
# Visualize data
ggplot(data = hare_select, aes(x = year, y = weight)) +
  geom_boxplot(aes(group = year,  y = weight), color = "wheat4",
               alpha = 0.8, outlier.shape = NA, varwidth = TRUE) +
  geom_jitter(aes(pch = age, color = season), 
             alpha = 0.6, width = 0.2, na.rm = FALSE) +
  facet_wrap(~season) +
  guides(color = FALSE) +
  labs(pch = "Age", x = "Year", y = "Weight [g]")+
  theme_bw()
```

```{r, include = FALSE}
# Wrangle table

hare_sum <- hare_select %>% 
  select(year, weight, season) %>% 
  group_by(year, season) %>% 
  summarize(
    sample_size = n(),
    mean_weight = mean(weight, na.rm = TRUE),
    se_weight = sd(weight, na.rm = TRUE) / sqrt(n())
  ) %>% 
  filter(sample_size > 100)

hare_table <- hare_sum %>% 
  rename("Mean Weight [g]" = mean_weight,
         "Standard Error" = se_weight,
         "Sample Size" = sample_size,
         "Year" = year,
         "Season" = season) 
```


```{r}
# Display table

kable(hare_table) %>%
  kable_styling(bootstrap_options = c("striped", "basic", "hover")) %>% 
  row_spec(c(1,3,5:7,9,11:13,15), color = "red") %>% 
  row_spec(c(2,4,6,8,10,14), bold = TRUE, color = "skyblue")
```


